// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv8R5SMl6SWvBRHVyDsRy8kOx4TTbpWdE',
    appId: '1:114206196396:web:bded349b9ea416f4e09509',
    messagingSenderId: '114206196396',
    projectId: 'zidanni-d4f6e',
    authDomain: 'zidanni-d4f6e.firebaseapp.com',
    storageBucket: 'zidanni-d4f6e.appspot.com',
    measurementId: 'G-2NKE63D93K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA9pmNPxHjehE1k2WWSUkECdw-HnDjsT8',
    appId: '1:114206196396:android:ee2fba408667c4f1e09509',
    messagingSenderId: '114206196396',
    projectId: 'zidanni-d4f6e',
    storageBucket: 'zidanni-d4f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcNKrVPtPVc8ged7QgvG6gjv0DxsUJ4yg',
    appId: '1:114206196396:ios:79a4831bf3e33a42e09509',
    messagingSenderId: '114206196396',
    projectId: 'zidanni-d4f6e',
    storageBucket: 'zidanni-d4f6e.appspot.com',
    iosBundleId: 'com.example.dmj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcNKrVPtPVc8ged7QgvG6gjv0DxsUJ4yg',
    appId: '1:114206196396:ios:a3242da23657852ae09509',
    messagingSenderId: '114206196396',
    projectId: 'zidanni-d4f6e',
    storageBucket: 'zidanni-d4f6e.appspot.com',
    iosBundleId: 'com.example.dmj.RunnerTests',
  );
}
